pip install pandas
pip install transformers==2.3.0 
pip install pytrec_eval 
pip install faiss-cpu==1.6.4 
pip install wget 
pip install scikit-learn 
pip install tensorboardX 
pip install urllib3 
pip install requests 
pip install jmespath 
pip install tqdm 
pip install setproctitle
pip install tables